
// This file has been generated by the GUI designer. Do not modify.
namespace XG.Client.TCP.GTK
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entryServer;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entryPort;

		private global::Gtk.Label label4;

		private global::Gtk.Entry entryPassword;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button btnConnect;

		private global::Gtk.Button btnDisconnect;

		private global::XG.Client.Widgets.GTK.MainWidget mainWidget;

		private global::Gtk.HSeparator hseparator2;

		private global::XG.Client.Widgets.GTK.StatusWidget statusWidget;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XG.Client.TCP.GTK.MainWindow
			this.Name = "XG.Client.TCP.GTK.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("XG Client TCP GTK");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Container child XG.Client.TCP.GTK.MainWindow.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(6));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Server");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryServer = new global::Gtk.Entry ();
			this.entryServer.CanFocus = true;
			this.entryServer.Name = "entryServer";
			this.entryServer.IsEditable = true;
			this.entryServer.WidthChars = 20;
			this.entryServer.InvisibleChar = '●';
			this.hbox6.Add (this.entryServer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryServer]));
			w2.Position = 1;
			w2.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Port");
			this.hbox6.Add (this.label6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryPort = new global::Gtk.Entry ();
			this.entryPort.CanFocus = true;
			this.entryPort.Name = "entryPort";
			this.entryPort.IsEditable = true;
			this.entryPort.WidthChars = 5;
			this.entryPort.InvisibleChar = '●';
			this.hbox6.Add (this.entryPort);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryPort]));
			w4.Position = 3;
			w4.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.hbox6.Add (this.label4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label4]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryPassword = new global::Gtk.Entry ();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.WidthChars = 20;
			this.entryPassword.Visibility = false;
			this.entryPassword.InvisibleChar = '●';
			this.hbox6.Add (this.entryPassword);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryPassword]));
			w6.Position = 5;
			w6.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox6.Add (this.fixed1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.fixed1]));
			w7.Position = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnConnect = new global::Gtk.Button ();
			this.btnConnect.CanFocus = true;
			this.btnConnect.Name = "btnConnect";
			this.btnConnect.UseUnderline = true;
			// Container child btnConnect.Gtk.Container+ContainerChild
			global::Gtk.Alignment w8 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w9 = new global::Gtk.HBox ();
			w9.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w10 = new global::Gtk.Image ();
			w9.Add (w10);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w12 = new global::Gtk.Label ();
			w12.LabelProp = global::Mono.Unix.Catalog.GetString ("_Connect");
			w12.UseUnderline = true;
			w9.Add (w12);
			w8.Add (w9);
			this.btnConnect.Add (w8);
			this.hbox6.Add (this.btnConnect);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnConnect]));
			w16.Position = 7;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnDisconnect = new global::Gtk.Button ();
			this.btnDisconnect.Sensitive = false;
			this.btnDisconnect.CanFocus = true;
			this.btnDisconnect.Name = "btnDisconnect";
			this.btnDisconnect.UseUnderline = true;
			// Container child btnDisconnect.Gtk.Container+ContainerChild
			global::Gtk.Alignment w17 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w18 = new global::Gtk.HBox ();
			w18.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w18.Add (w19);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w21 = new global::Gtk.Label ();
			w21.LabelProp = global::Mono.Unix.Catalog.GetString ("_Disconnect");
			w21.UseUnderline = true;
			w18.Add (w21);
			w17.Add (w18);
			this.btnDisconnect.Add (w17);
			this.hbox6.Add (this.btnDisconnect);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnDisconnect]));
			w25.Position = 8;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox5.Add (this.hbox6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.mainWidget = new global::XG.Client.Widgets.GTK.MainWidget ();
			this.mainWidget.Events = ((global::Gdk.EventMask)(256));
			this.mainWidget.Name = "mainWidget";
			this.vbox5.Add (this.mainWidget);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.mainWidget]));
			w27.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox5.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator2]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.statusWidget = new global::XG.Client.Widgets.GTK.StatusWidget ();
			this.statusWidget.Events = ((global::Gdk.EventMask)(256));
			this.statusWidget.Name = "statusWidget";
			this.vbox5.Add (this.statusWidget);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.statusWidget]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.entryServer.Activated += new global::System.EventHandler (this.entryServerActivated);
			this.entryPort.Activated += new global::System.EventHandler (this.entryPortActivated);
			this.entryPassword.Activated += new global::System.EventHandler (this.entryPasswordActivated);
			this.btnConnect.Clicked += new global::System.EventHandler (this.btnConnectClicked);
			this.btnDisconnect.Clicked += new global::System.EventHandler (this.btnDisconnectHandler);
		}
	}
}
