// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XG.Client.Widgets.GTK {
    
    
    public partial class MainWidget {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.HPaned hpanedIrc;
        
        private Gtk.VBox vbox4;
        
        private Gtk.VPaned vpaned5;
        
        private Gtk.VBox vbox5;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button btnAddServer;
        
        private Gtk.Button btnAddChannel;
        
        private Gtk.Button btnRemoveObject;
        
        private XG.Client.Widgets.GTK.ServerChannelWidget serverchannelWidget;
        
        private XG.Client.Widgets.GTK.SearchWidget searchWidget;
        
        private Gtk.HBox hboxSearch;
        
        private Gtk.Entry entrySearch;
        
        private Gtk.Button btnSearch;
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox2;
        
        private Gtk.CheckButton chkOfflineBots;
        
        private Gtk.VPaned vpaned4;
        
        private XG.Client.Widgets.GTK.BotWidget botWidget;
        
        private XG.Client.Widgets.GTK.PacketWidget packetWidget;
        
        private Gtk.Label label1;
        
        private Gtk.VBox vboxFile;
        
        private Gtk.HBox hbox3;
        
        private Gtk.CheckButton chkFilesReady;
        
        private XG.Client.Widgets.GTK.FileWidget fileWidget;
        
        private Gtk.Label label2;
        
        private Gtk.VBox vbox7;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment9;
        
        private Gtk.Label GtkLabel12;
        
        private Gtk.Label label3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget XG.Client.Widgets.GTK.MainWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "XG.Client.Widgets.GTK.MainWidget";
            // Container child XG.Client.Widgets.GTK.MainWidget.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 2;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.hpanedIrc = new Gtk.HPaned();
            this.hpanedIrc.CanFocus = true;
            this.hpanedIrc.Name = "hpanedIrc";
            this.hpanedIrc.Position = 220;
            this.hpanedIrc.BorderWidth = ((uint)(6));
            // Container child hpanedIrc.Gtk.Paned+PanedChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.vpaned5 = new Gtk.VPaned();
            this.vpaned5.CanFocus = true;
            this.vpaned5.Name = "vpaned5";
            this.vpaned5.Position = 246;
            // Container child vpaned5.Gtk.Paned+PanedChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnAddServer = new Gtk.Button();
            this.btnAddServer.CanFocus = true;
            this.btnAddServer.Name = "btnAddServer";
            // Container child btnAddServer.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w5.LabelProp = Mono.Unix.Catalog.GetString("Add");
            w2.Add(w5);
            w1.Add(w2);
            this.btnAddServer.Add(w1);
            this.hbox1.Add(this.btnAddServer);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnAddServer]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnAddChannel = new Gtk.Button();
            this.btnAddChannel.CanFocus = true;
            this.btnAddChannel.Name = "btnAddChannel";
            // Container child btnAddChannel.Gtk.Container+ContainerChild
            Gtk.Alignment w10 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w11 = new Gtk.HBox();
            w11.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w12 = new Gtk.Image();
            w11.Add(w12);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w14 = new Gtk.Label();
            w14.LabelProp = Mono.Unix.Catalog.GetString("Add");
            w11.Add(w14);
            w10.Add(w11);
            this.btnAddChannel.Add(w10);
            this.hbox1.Add(this.btnAddChannel);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnAddChannel]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.btnRemoveObject = new Gtk.Button();
            this.btnRemoveObject.CanFocus = true;
            this.btnRemoveObject.Name = "btnRemoveObject";
            // Container child btnRemoveObject.Gtk.Container+ContainerChild
            Gtk.Alignment w19 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w20 = new Gtk.HBox();
            w20.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w21 = new Gtk.Image();
            w20.Add(w21);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w23 = new Gtk.Label();
            w23.LabelProp = Mono.Unix.Catalog.GetString("Remove");
            w20.Add(w23);
            w19.Add(w20);
            this.btnRemoveObject.Add(w19);
            this.hbox1.Add(this.btnRemoveObject);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox1[this.btnRemoveObject]));
            w27.Position = 2;
            w27.Expand = false;
            w27.Fill = false;
            this.vbox5.Add(this.hbox1);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
            w28.Position = 0;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.serverchannelWidget = new XG.Client.Widgets.GTK.ServerChannelWidget();
            this.serverchannelWidget.Events = ((Gdk.EventMask)(256));
            this.serverchannelWidget.Name = "serverchannelWidget";
            this.vbox5.Add(this.serverchannelWidget);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox5[this.serverchannelWidget]));
            w29.Position = 1;
            this.vpaned5.Add(this.vbox5);
            Gtk.Paned.PanedChild w30 = ((Gtk.Paned.PanedChild)(this.vpaned5[this.vbox5]));
            w30.Resize = false;
            // Container child vpaned5.Gtk.Paned+PanedChild
            this.searchWidget = new XG.Client.Widgets.GTK.SearchWidget();
            this.searchWidget.Events = ((Gdk.EventMask)(256));
            this.searchWidget.Name = "searchWidget";
            this.vpaned5.Add(this.searchWidget);
            this.vbox4.Add(this.vpaned5);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.vbox4[this.vpaned5]));
            w32.Position = 0;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hboxSearch = new Gtk.HBox();
            this.hboxSearch.Name = "hboxSearch";
            this.hboxSearch.Spacing = 6;
            // Container child hboxSearch.Gtk.Box+BoxChild
            this.entrySearch = new Gtk.Entry();
            this.entrySearch.CanFocus = true;
            this.entrySearch.Name = "entrySearch";
            this.entrySearch.IsEditable = true;
            this.entrySearch.InvisibleChar = '●';
            this.hboxSearch.Add(this.entrySearch);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hboxSearch[this.entrySearch]));
            w33.Position = 0;
            // Container child hboxSearch.Gtk.Box+BoxChild
            this.btnSearch = new Gtk.Button();
            this.btnSearch.CanFocus = true;
            this.btnSearch.Name = "btnSearch";
            // Container child btnSearch.Gtk.Container+ContainerChild
            Gtk.Alignment w34 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w35 = new Gtk.HBox();
            w35.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w36 = new Gtk.Image();
            w35.Add(w36);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w38 = new Gtk.Label();
            w38.LabelProp = Mono.Unix.Catalog.GetString("Search");
            w35.Add(w38);
            w34.Add(w35);
            this.btnSearch.Add(w34);
            this.hboxSearch.Add(this.btnSearch);
            Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hboxSearch[this.btnSearch]));
            w42.Position = 1;
            w42.Expand = false;
            w42.Fill = false;
            this.vbox4.Add(this.hboxSearch);
            Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.vbox4[this.hboxSearch]));
            w43.Position = 1;
            w43.Expand = false;
            w43.Fill = false;
            this.hpanedIrc.Add(this.vbox4);
            Gtk.Paned.PanedChild w44 = ((Gtk.Paned.PanedChild)(this.hpanedIrc[this.vbox4]));
            w44.Resize = false;
            // Container child hpanedIrc.Gtk.Paned+PanedChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.chkOfflineBots = new Gtk.CheckButton();
            this.chkOfflineBots.CanFocus = true;
            this.chkOfflineBots.Name = "chkOfflineBots";
            this.chkOfflineBots.Label = Mono.Unix.Catalog.GetString("Show offline bots");
            this.chkOfflineBots.Active = true;
            this.chkOfflineBots.DrawIndicator = true;
            this.chkOfflineBots.UseUnderline = true;
            this.hbox2.Add(this.chkOfflineBots);
            Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkOfflineBots]));
            w45.Position = 0;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w46.Position = 0;
            w46.Expand = false;
            w46.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.vpaned4 = new Gtk.VPaned();
            this.vpaned4.CanFocus = true;
            this.vpaned4.Name = "vpaned4";
            this.vpaned4.Position = 220;
            // Container child vpaned4.Gtk.Paned+PanedChild
            this.botWidget = new XG.Client.Widgets.GTK.BotWidget();
            this.botWidget.Events = ((Gdk.EventMask)(256));
            this.botWidget.Name = "botWidget";
            this.vpaned4.Add(this.botWidget);
            Gtk.Paned.PanedChild w47 = ((Gtk.Paned.PanedChild)(this.vpaned4[this.botWidget]));
            w47.Resize = false;
            // Container child vpaned4.Gtk.Paned+PanedChild
            this.packetWidget = new XG.Client.Widgets.GTK.PacketWidget();
            this.packetWidget.Events = ((Gdk.EventMask)(256));
            this.packetWidget.Name = "packetWidget";
            this.vpaned4.Add(this.packetWidget);
            this.vbox2.Add(this.vpaned4);
            Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox2[this.vpaned4]));
            w49.Position = 1;
            this.hpanedIrc.Add(this.vbox2);
            this.notebook1.Add(this.hpanedIrc);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xpad = 6;
            this.label1.Ypad = 2;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("IRC View");
            this.notebook1.SetTabLabel(this.hpanedIrc, this.label1);
            this.label1.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vboxFile = new Gtk.VBox();
            this.vboxFile.Name = "vboxFile";
            this.vboxFile.Spacing = 6;
            this.vboxFile.BorderWidth = ((uint)(6));
            // Container child vboxFile.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.chkFilesReady = new Gtk.CheckButton();
            this.chkFilesReady.CanFocus = true;
            this.chkFilesReady.Name = "chkFilesReady";
            this.chkFilesReady.Label = Mono.Unix.Catalog.GetString("Show ready files");
            this.chkFilesReady.Active = true;
            this.chkFilesReady.DrawIndicator = true;
            this.chkFilesReady.UseUnderline = true;
            this.hbox3.Add(this.chkFilesReady);
            Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.hbox3[this.chkFilesReady]));
            w52.Position = 0;
            this.vboxFile.Add(this.hbox3);
            Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.vboxFile[this.hbox3]));
            w53.Position = 0;
            w53.Expand = false;
            w53.Fill = false;
            // Container child vboxFile.Gtk.Box+BoxChild
            this.fileWidget = new XG.Client.Widgets.GTK.FileWidget();
            this.fileWidget.Events = ((Gdk.EventMask)(256));
            this.fileWidget.Name = "fileWidget";
            this.vboxFile.Add(this.fileWidget);
            Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(this.vboxFile[this.fileWidget]));
            w54.Position = 1;
            this.notebook1.Add(this.vboxFile);
            Gtk.Notebook.NotebookChild w55 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vboxFile]));
            w55.Position = 1;
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xpad = 6;
            this.label2.Ypad = 2;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("File View");
            this.notebook1.SetTabLabel(this.vboxFile, this.label2);
            this.label2.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox7 = new Gtk.VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = 6;
            this.vbox7.BorderWidth = ((uint)(6));
            // Container child vbox7.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment9 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment9.Name = "GtkAlignment9";
            this.GtkAlignment9.LeftPadding = ((uint)(12));
            this.frame2.Add(this.GtkAlignment9);
            this.GtkLabel12 = new Gtk.Label();
            this.GtkLabel12.Name = "GtkLabel12";
            this.GtkLabel12.Xpad = 5;
            this.GtkLabel12.Ypad = 5;
            this.GtkLabel12.LabelProp = Mono.Unix.Catalog.GetString("<b>Client Settings</b>");
            this.GtkLabel12.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel12;
            this.vbox7.Add(this.frame2);
            Gtk.Box.BoxChild w57 = ((Gtk.Box.BoxChild)(this.vbox7[this.frame2]));
            w57.Position = 0;
            this.notebook1.Add(this.vbox7);
            Gtk.Notebook.NotebookChild w58 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox7]));
            w58.Position = 2;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xpad = 6;
            this.label3.Ypad = 2;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Settings");
            this.notebook1.SetTabLabel(this.vbox7, this.label3);
            this.label3.ShowAll();
            this.Add(this.notebook1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.btnAddServer.Clicked += new System.EventHandler(this.btnAddServer_Clicked);
            this.btnAddChannel.Clicked += new System.EventHandler(this.btnAddChannel_Clicked);
            this.btnRemoveObject.Clicked += new System.EventHandler(this.btnRemoveObject_Clicked);
            this.entrySearch.Activated += new System.EventHandler(this.entrySearch_Activated);
            this.btnSearch.Clicked += new System.EventHandler(this.btnSearch_Clicked);
            this.chkOfflineBots.Toggled += new System.EventHandler(this.chkOfflineBots_Toggled);
            this.chkFilesReady.Toggled += new System.EventHandler(this.chkFilesReady_Toggled);
        }
    }
}
