// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XG.Client.Widgets.GTK {
    
    
    public partial class ViewWidget {
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeView;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget XG.Client.Widgets.GTK.ViewWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "XG.Client.Widgets.GTK.ViewWidget";
            // Container child XG.Client.Widgets.GTK.ViewWidget.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeView = new Gtk.TreeView();
            this.treeView.CanFocus = true;
            this.treeView.Name = "treeView";
            this.GtkScrolledWindow.Add(this.treeView);
            this.Add(this.GtkScrolledWindow);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.treeView.CursorChanged += new System.EventHandler(this.treeViewCursorChanged);
            this.treeView.RowActivated += new Gtk.RowActivatedHandler(this.treeViewRowActivated);
        }
    }
}
