// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XG.Client.Widgets.GTK {
    
    
    public partial class StatusWidget {
        
        private Gtk.HBox hbox;
        
        private Gtk.Image imageServer;
        
        private Gtk.Label infoServer;
        
        private Gtk.Image imageChannel;
        
        private Gtk.Label infoChannel;
        
        private Gtk.Image imageBot;
        
        private Gtk.Label infoBot;
        
        private Gtk.Image imagePacket;
        
        private Gtk.Label infoPacket;
        
        private Gtk.Image imageDownloadSpeed;
        
        private Gtk.Label infoSpeed;
        
        private Gtk.Image imageFiles;
        
        private Gtk.Label infoFiles;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget XG.Client.Widgets.GTK.StatusWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "XG.Client.Widgets.GTK.StatusWidget";
            // Container child XG.Client.Widgets.GTK.StatusWidget.Gtk.Container+ContainerChild
            this.hbox = new Gtk.HBox();
            this.hbox.HeightRequest = 20;
            this.hbox.Name = "hbox";
            this.hbox.Spacing = 6;
            // Container child hbox.Gtk.Box+BoxChild
            this.imageServer = new Gtk.Image();
            this.imageServer.Name = "imageServer";
            this.hbox.Add(this.imageServer);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox[this.imageServer]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.infoServer = new Gtk.Label();
            this.infoServer.WidthRequest = 90;
            this.infoServer.Name = "infoServer";
            this.hbox.Add(this.infoServer);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox[this.infoServer]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.imageChannel = new Gtk.Image();
            this.imageChannel.Name = "imageChannel";
            this.hbox.Add(this.imageChannel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox[this.imageChannel]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.infoChannel = new Gtk.Label();
            this.infoChannel.WidthRequest = 90;
            this.infoChannel.Name = "infoChannel";
            this.hbox.Add(this.infoChannel);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox[this.infoChannel]));
            w4.Position = 3;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.imageBot = new Gtk.Image();
            this.imageBot.Name = "imageBot";
            this.hbox.Add(this.imageBot);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox[this.imageBot]));
            w5.Position = 4;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.infoBot = new Gtk.Label();
            this.infoBot.WidthRequest = 90;
            this.infoBot.Name = "infoBot";
            this.hbox.Add(this.infoBot);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox[this.infoBot]));
            w6.Position = 5;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.imagePacket = new Gtk.Image();
            this.imagePacket.Name = "imagePacket";
            this.hbox.Add(this.imagePacket);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox[this.imagePacket]));
            w7.Position = 6;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.infoPacket = new Gtk.Label();
            this.infoPacket.WidthRequest = 90;
            this.infoPacket.Name = "infoPacket";
            this.hbox.Add(this.infoPacket);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox[this.infoPacket]));
            w8.Position = 7;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.imageDownloadSpeed = new Gtk.Image();
            this.imageDownloadSpeed.Name = "imageDownloadSpeed";
            this.hbox.Add(this.imageDownloadSpeed);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox[this.imageDownloadSpeed]));
            w9.Position = 8;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.infoSpeed = new Gtk.Label();
            this.infoSpeed.WidthRequest = 90;
            this.infoSpeed.Name = "infoSpeed";
            this.hbox.Add(this.infoSpeed);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox[this.infoSpeed]));
            w10.Position = 9;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.imageFiles = new Gtk.Image();
            this.imageFiles.Name = "imageFiles";
            this.hbox.Add(this.imageFiles);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox[this.imageFiles]));
            w11.Position = 10;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.infoFiles = new Gtk.Label();
            this.infoFiles.WidthRequest = 120;
            this.infoFiles.Name = "infoFiles";
            this.hbox.Add(this.infoFiles);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox[this.infoFiles]));
            w12.Position = 11;
            w12.Expand = false;
            w12.Fill = false;
            this.Add(this.hbox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
